// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_region

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RegionDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"country": schema.StringAttribute{
				Computed:            true,
				Description:         "Country of the region",
				MarkdownDescription: "Country of the region",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Description of the region",
				MarkdownDescription: "Description of the region",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the region",
				MarkdownDescription: "Name of the region",
			},
			"region_provider": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"provider_type": schema.StringAttribute{
						Computed:            true,
						Description:         "Actual infrastructure backing the region",
						MarkdownDescription: "Actual infrastructure backing the region",
					},
					"region_name": schema.StringAttribute{
						Computed:            true,
						Description:         "Name of the region",
						MarkdownDescription: "Name of the region",
					},
				},
				CustomType: RegionProviderType{
					ObjectType: types.ObjectType{
						AttrTypes: RegionProviderValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type RegionModel struct {
	Country        types.String        `tfsdk:"country"`
	Description    types.String        `tfsdk:"description"`
	Name           types.String        `tfsdk:"name"`
	RegionProvider RegionProviderValue `tfsdk:"region_provider"`
}

var _ basetypes.ObjectTypable = RegionProviderType{}

type RegionProviderType struct {
	basetypes.ObjectType
}

func (t RegionProviderType) Equal(o attr.Type) bool {
	other, ok := o.(RegionProviderType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RegionProviderType) String() string {
	return "RegionProviderType"
}

func (t RegionProviderType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	providerTypeAttribute, ok := attributes["provider_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider_type is missing from object`)

		return nil, diags
	}

	providerTypeVal, ok := providerTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider_type expected to be basetypes.StringValue, was: %T`, providerTypeAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return nil, diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RegionProviderValue{
		ProviderType: providerTypeVal,
		RegionName:   regionNameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewRegionProviderValueNull() RegionProviderValue {
	return RegionProviderValue{
		state: attr.ValueStateNull,
	}
}

func NewRegionProviderValueUnknown() RegionProviderValue {
	return RegionProviderValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRegionProviderValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RegionProviderValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RegionProviderValue Attribute Value",
				"While creating a RegionProviderValue value, a missing attribute value was detected. "+
					"A RegionProviderValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegionProviderValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RegionProviderValue Attribute Type",
				"While creating a RegionProviderValue value, an invalid attribute value was detected. "+
					"A RegionProviderValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegionProviderValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RegionProviderValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RegionProviderValue Attribute Value",
				"While creating a RegionProviderValue value, an extra attribute value was detected. "+
					"A RegionProviderValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RegionProviderValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRegionProviderValueUnknown(), diags
	}

	providerTypeAttribute, ok := attributes["provider_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider_type is missing from object`)

		return NewRegionProviderValueUnknown(), diags
	}

	providerTypeVal, ok := providerTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider_type expected to be basetypes.StringValue, was: %T`, providerTypeAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return NewRegionProviderValueUnknown(), diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	if diags.HasError() {
		return NewRegionProviderValueUnknown(), diags
	}

	return RegionProviderValue{
		ProviderType: providerTypeVal,
		RegionName:   regionNameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewRegionProviderValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RegionProviderValue {
	object, diags := NewRegionProviderValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRegionProviderValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RegionProviderType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRegionProviderValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRegionProviderValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRegionProviderValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRegionProviderValueMust(RegionProviderValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RegionProviderType) ValueType(ctx context.Context) attr.Value {
	return RegionProviderValue{}
}

var _ basetypes.ObjectValuable = RegionProviderValue{}

type RegionProviderValue struct {
	ProviderType basetypes.StringValue `tfsdk:"provider_type"`
	RegionName   basetypes.StringValue `tfsdk:"region_name"`
	state        attr.ValueState
}

func (v RegionProviderValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["provider_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ProviderType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provider_type"] = val

		val, err = v.RegionName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RegionProviderValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RegionProviderValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RegionProviderValue) String() string {
	return "RegionProviderValue"
}

func (v RegionProviderValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"provider_type": basetypes.StringType{},
			"region_name":   basetypes.StringType{},
		},
		map[string]attr.Value{
			"provider_type": v.ProviderType,
			"region_name":   v.RegionName,
		})

	return objVal, diags
}

func (v RegionProviderValue) Equal(o attr.Value) bool {
	other, ok := o.(RegionProviderValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ProviderType.Equal(other.ProviderType) {
		return false
	}

	if !v.RegionName.Equal(other.RegionName) {
		return false
	}

	return true
}

func (v RegionProviderValue) Type(ctx context.Context) attr.Type {
	return RegionProviderType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RegionProviderValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"provider_type": basetypes.StringType{},
		"region_name":   basetypes.StringType{},
	}
}
