provider:
  name: spot

resources:
  # Ref: https://spot.rackspace.com/docs/rxt_spot_api#readngpcrxtiov1namespacedcloudspace
  cloudspace:
    create:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/cloudspaces
      method: POST
    read:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/cloudspaces/{name}
      method: GET
    update:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/cloudspaces/{name}
      method: PUT
    delete:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/cloudspaces/{name}
      method: DELETE

  spotnodepools:
    create:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/spotnodepools
      method: POST
    read:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/spotnodepools/{name}
      method: GET
    update:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/spotnodepools/{name}
      method: PUT
    delete:
      path: /apis/ngpc.rxt.io/v1/namespaces/{namespace}/spotnodepools/{name}
      method: DELETE

