// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_rxtspot

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func RxtspotProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type RxtspotModel struct {
}
