// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_rackspacespot

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func RackspacespotProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type RackspacespotModel struct {
}
