// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_spot

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func SpotProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type SpotModel struct {
}
